# Generated by Django 6.0.5 on 2026-06-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_match_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score_team1',
            field=models.IntegerField(blank=True, null=True, verbose_name='امتیاز تیم اول'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_team2',
            field=models.IntegerField(blank=True, null=True, verbose_name='امتیاز تیم دوم'),
        ),
    ]
