# Generated by Django 6.0.5 on 2026-06-22 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_match_report'),
        ('teams', '0003_alter_team_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPlayerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='امتیاز')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_scores', to='games.match', verbose_name='مسابقه')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_scores', to='teams.team', verbose_name='تیم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to=settings.AUTH_USER_MODEL, verbose_name='بازیکن')),
            ],
            options={
                'verbose_name': 'امتیاز بازیکن',
                'verbose_name_plural': 'امتیازات بازیکنان',
                'unique_together': {('match', 'user')},
            },
        ),
    ]
