# Generated by Django 6.0.5 on 2026-06-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_matchplayerscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayerscore',
            name='completion_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='زمان (ثانیه)'),
        ),
    ]
