# Generated by Django 6.0.5 on 2026-08-02 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_quizcategory_quizquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizMatchQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='ترتیب سؤال')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='games.match', verbose_name='مسابقه')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='games.quizquestion', verbose_name='سؤال')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('match', 'question')},
            },
        ),
    ]
