# Generated by Django 6.0.5 on 2026-08-02 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_quizmatchquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='پاسخ انتخاب\u200cشده')),
                ('is_correct', models.BooleanField(default=False, verbose_name='درست است؟')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان پاسخ')),
                ('match_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='games.quizmatchquestion', verbose_name='سؤال مسابقه')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='games.gamesession', verbose_name='جلسه بازی')),
            ],
            options={
                'unique_together': {('session', 'match_question')},
            },
        ),
    ]
