# Generated by Django 6.0.5 on 2026-08-04 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_quizanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSessionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.JSONField(default=dict, verbose_name='وضعیت بازی')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_state', to='games.gamesession', verbose_name='جلسه بازی')),
            ],
        ),
    ]
