# Generated by Django 6.0.5 on 2026-08-06 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_category'),
        ('games', '0012_gamesessionstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_questions', to='competitions.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.DeleteModel(
            name='QuizCategory',
        ),
    ]
