# Generated by Django 6.0.5 on 2026-08-11 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_remove_tournament_question_count_and_more'),
        ('games', '0013_alter_quizquestion_category_delete_quizcategory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizmatchquestion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='match',
            name='tournament',
        ),
        migrations.AddField(
            model_name='match',
            name='pairing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='match', to='competitions.pairing', verbose_name='Pairing'),
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competitions.round', verbose_name='دور'),
        ),
        migrations.AddField(
            model_name='quizmatchquestion',
            name='round_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='match_questions', to='competitions.roundquestion', verbose_name='سؤال دور'),
        ),
        migrations.AddConstraint(
            model_name='quizmatchquestion',
            constraint=models.UniqueConstraint(fields=('match', 'round_question'), name='unique_round_question_per_match'),
        ),
        migrations.AddConstraint(
            model_name='quizmatchquestion',
            constraint=models.UniqueConstraint(fields=('match', 'order'), name='unique_question_order_per_match'),
        ),
        migrations.RemoveField(
            model_name='quizmatchquestion',
            name='question',
        ),
    ]
