# Generated by Django 6.0.5 on 2026-08-14 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_alter_quizmatchquestion_unique_together_and_more'),
        ('teams', '0003_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='forfeit_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forfeited_matches', to='teams.team', verbose_name='تیم حاضر در فورفیت'),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('active', 'در حال بازی'), ('completed', 'تکمیل شده'), ('forfeit', 'فورفیت شده')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
    ]
