# Generated by Django 6.0.5 on 2026-08-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_match_forfeit_team_match_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('active', 'در حال بازی'), ('completed', 'تکمیل شده'), ('forfeit', 'فورفیت شده'), ('double_forfeit', 'عدم حضور دو طرف')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
    ]
