# Generated by Django 6.0.5 on 2026-06-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_tournament_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametype',
            name='key',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='کلید فنی'),
        ),
    ]
