# Generated by Django 6.0.5 on 2026-06-25 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_gametype_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='game_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='competitions.gametype', verbose_name='نوع بازی'),
        ),
    ]
