# Generated by Django 6.0.5 on 2026-08-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='question_count',
            field=models.PositiveIntegerField(default=10, verbose_name='تعداد سوالات هر مسابقه'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='question_difficulty',
            field=models.CharField(choices=[('easy', 'آسان'), ('medium', 'متوسط'), ('hard', 'سخت')], default='easy', max_length=10, verbose_name='درجه سختی سوالات'),
        ),
    ]
