# Generated by Django 6.0.5 on 2026-08-11 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_tournament_question_count_and_more'),
        ('games', '0013_alter_quizquestion_category_delete_quizcategory'),
        ('teams', '0003_alter_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='question_count',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='question_difficulty',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='subject',
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='شماره دور')),
                ('status', models.CharField(choices=[('scheduled', 'زمان\u200cبندی شده'), ('active', 'در حال برگزاری'), ('finished', 'تمام شده')], default='scheduled', max_length=20, verbose_name='وضعیت')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('question_difficulty', models.CharField(choices=[('easy', 'آسان'), ('medium', 'متوسط'), ('hard', 'سخت')], default='easy', max_length=10, verbose_name='درجه سختی سوالات')),
                ('question_count', models.PositiveIntegerField(default=10, verbose_name='تعداد سوالات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rounds', to='competitions.subject', verbose_name='موضوع')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='competitions.tournament', verbose_name='مسابقات')),
            ],
            options={
                'ordering': ['tournament', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings_as_team1', to='teams.team', verbose_name='تیم اول')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings_as_team2', to='teams.team', verbose_name='تیم دوم')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='competitions.round', verbose_name='دور')),
            ],
        ),
        migrations.CreateModel(
            name='RoundBye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=3, verbose_name='امتیاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bye', to='competitions.round', verbose_name='دور')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_byes', to='teams.team', verbose_name='تیم')),
            ],
        ),
        migrations.CreateModel(
            name='RoundQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='ترتیب سؤال')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='round_questions', to='games.quizquestion', verbose_name='سؤال')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='competitions.round', verbose_name='دور')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(fields=('tournament', 'number'), name='unique_round_number_per_tournament'),
        ),
        migrations.AddConstraint(
            model_name='pairing',
            constraint=models.UniqueConstraint(fields=('round', 'team1'), name='unique_team1_pairing_per_round'),
        ),
        migrations.AddConstraint(
            model_name='pairing',
            constraint=models.UniqueConstraint(fields=('round', 'team2'), name='unique_team2_pairing_per_round'),
        ),
        migrations.AddConstraint(
            model_name='roundbye',
            constraint=models.UniqueConstraint(fields=('round', 'team'), name='unique_bye_team_per_round'),
        ),
        migrations.AddConstraint(
            model_name='roundquestion',
            constraint=models.UniqueConstraint(fields=('round', 'question'), name='unique_question_per_round'),
        ),
        migrations.AddConstraint(
            model_name='roundquestion',
            constraint=models.UniqueConstraint(fields=('round', 'order'), name='unique_question_order_per_round'),
        ),
    ]
