# Generated by Django 6.0.5 on 2026-08-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_remove_tournament_question_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='total_rounds',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد کل دورها'),
            preserve_default=False,
        ),
    ]
