# Generated by Django 6.0.5 on 2026-09-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_tournament_total_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments/', verbose_name='تصویر لیگ'),
        ),
    ]
